import 'package:flutter/material.dart';

class TermsAndConditionsPage extends StatefulWidget {
  const TermsAndConditionsPage({super.key});

  @override
  TermsAndConditionsPageState createState() => TermsAndConditionsPageState();
}

class TermsAndConditionsPageState extends State<TermsAndConditionsPage> {
  bool isChecked = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Privacy Policy"),
        backgroundColor: const Color(0xFFF6F6F6),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text(
                "Privacy Policy",
                style: TextStyle(
                  fontSize: 22.0,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const SizedBox(height: 8.0),
              const Text(
                "Last updated: November 13, 2024",
                style: TextStyle(fontSize: 12.0, fontStyle: FontStyle.italic),
              ),
              const SizedBox(height: 14.0),
              const Text(
                "This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.\n\n"
                "We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.",
                style: TextStyle(fontSize: 12.0),
              ),
              const SizedBox(height: 14.0),
              const Text(
                "Interpretation and Definitions",
                style: TextStyle(
                  fontSize: 14.0,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const SizedBox(height: 8.0),
              const Text(
                "Interpretation",
                style: TextStyle(
                  fontSize: 14.0,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const Text(
                "The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.",
                style: TextStyle(fontSize: 12.0),
              ),
              const SizedBox(height: 8.0),
              const Text(
                "Definitions",
                style: TextStyle(
                  fontSize: 14.0,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const Text(
                "For the purposes of this Privacy Policy:\n\n"
                "- Account means a unique account created for You to access our Service or parts of our Service.\n"
                "- Affiliate means an entity that controls, is controlled by, or is under common control with a party, where 'control' means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.\n"
                "- Application refers to SyncBranch, the software program provided by the Company.\n"
                "- Company (referred to as either 'the Company,' 'We,' 'Us' or 'Our' in this Agreement) refers to SyncBranch.\n"
                "- Country refers to: Turkey.\n"
                "- Device means any device that can access the Service, such as a computer, a cellphone or a digital tablet.\n"
                "- Personal Data is any information that relates to an identified or identifiable individual.\n"
                "- Service refers to the Application.\n"
                "- Service Provider means any natural or legal person who processes the data on behalf of the Company.\n"
                "- Third-party Social Media Service refers to any website or social network website through which a User can log in or create an account to use the Service.\n"
                "- Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).\n"
                "- You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.",
                style: TextStyle(fontSize: 12.0),
              ),
              const SizedBox(height: 14.0),
              const Text(
                "Collecting and Using Your Personal Data",
                style: TextStyle(
                  fontSize: 14.0,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const SizedBox(height: 8.0),
              const Text(
                "Types of Data Collected",
                style: TextStyle(fontSize: 14.0, fontWeight: FontWeight.bold),
              ),
              const Text(
                "Personal Data\n\n"
                "While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:\n"
                "- Email address\n"
                "- First name and last name\n"
                "- Phone number\n\n"
                "Usage Data\n\n"
                "Usage Data is collected automatically when using the Service. It may include details like your Device's IP address, browser type, the pages you visit, and time spent on each page.\n\n"
                "When You access the Service by or through a mobile device, We may collect information such as:\n"
                "- Type of mobile device\n"
                "- Mobile device unique ID\n"
                "- IP address\n"
                "- Mobile operating system\n"
                "- Mobile browser type\n\n"
                "We may also collect data your browser sends whenever You access the Service.",
                style: TextStyle(fontSize: 12.0),
              ),
              const SizedBox(height: 14.0),
              const Text(
                "Information from Third-Party Social Media Services",
                style: TextStyle(
                  fontSize: 14.0,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const Text(
                "The Company allows You to create an account and log in to use the Service through Third-party Social Media Services, such as:\n\n"
                "- Google\n"
                "- Spotify\n\n"
                "If You register through a Third-Party Social Media Service, We may collect Personal data linked to Your account, such as Your name, email, activities, and contact list.",
                style: TextStyle(fontSize: 12.0),
              ),
              const SizedBox(height: 14.0),
              const Text(
                "Use of Your Personal Data",
                style: TextStyle(
                  fontSize: 14.0,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const Text(
                "The Company may use Personal Data for the following purposes:\n\n"
                "- To provide and maintain our Service**, including to monitor usage.\n"
                "- To manage Your Account**: managing Your registration as a user.\n"
                "- For the performance of a contract**: fulfilling contracts related to purchased items or services.\n"
                "- To contact You**: providing updates via email, calls, SMS, or push notifications.\n"
                "- To provide You with promotions and general information** about similar goods or services, unless opted out.\n"
                "- To manage Your requests**: attending and responding to inquiries.\n"
                "- For business transfers**: if involved in mergers or similar business processes.\n"
                "- For other purposes**: including data analysis, usage trends, and enhancing user experience.",
                style: TextStyle(fontSize: 12.0),
              ),
              const SizedBox(height: 14.0),
              const Text(
                "We may share Your personal information in the following situations:",
                style: TextStyle(
                  fontSize: 14.0,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const Text(
                "- With Service Providers**: for usage monitoring and contact.\n"
                "- For business transfers**: during negotiations or sales of Company assets.\n"
                "- With Affiliates**: to affiliated entities that honor this Privacy Policy.\n"
                "- With business partners**: to offer related products or services.\n"
                "- With other users**: when interacting publicly, information may be visible to all users.\n"
                "- With Your consent**: as permitted by You for other purposes.",
                style: TextStyle(fontSize: 12.0),
              ),
              const SizedBox(height: 14.0),
              const CheckboxListTile(
                title: Text(
                    "I have read and approve the terms of use and privacy policy."),
                value: false,
                onChanged: null,
                controlAffinity: ListTileControlAffinity.leading,
              ),
              Center(
                child: ElevatedButton(
                  onPressed: isChecked ? () {} : null,
                  child: const Text("Continue"),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
